Bachelor/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^', include('StudentPoll.urls')),
    url(r'^admin/', admin.site.urls),
]

StudentPoll/urls.py
from django.conf.urls import url
from .models import Faculty
from . import views

app_name = 'StudentPoll'

urlpatterns = [
    #Actual Views
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^vote/$', views.Vote_View.as_view(), name='Vote'),
    url(r'^statistics/$', views.Statistics.as_view(), name='Statistics'),
    url(r'^login/$', views.Login.as_view(), name='Login'),
    url(r'^poll/admin/$', views.PollAdmin.as_view(), name='PollAdmin'),

    #Some Functions
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^pollAdd/$', views.pollAdd_view, name='pollAdd'),
    url(r'^categoryAdd/$', views.categoryAdd_view, name='categoryAdd'),
    url(r'^editState/$', views.editState_view, name='editState'),

    #Ajax Requests
    url(r'^ajax/filterGroups/$', views.filterGroups_view, name='filterGroups'),
    url(r'^ajax/getSubjects/$', views.getSubjects_view, name='getSubjects'),

]

StudentPoll/models.py
from django.db import models
import datetime

# Create your models here.


class Faculty(models.Model):
    facultyName = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.facultyName


class Category(models.Model):
    categoryName = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.categoryName


class Vote(models.Model):
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    startYear = models.SmallIntegerField(default=datetime.datetime.now().year)
    endYear = models.SmallIntegerField(default=datetime.datetime.now().year+1)
    half = models.SmallIntegerField(choices={(1, '1'), (2, '2')}, default=1)
    isActive = models.BooleanField('Активувати', default=False)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return "{} : {}/{} : {} половина".format(self.faculty, self.startYear, self.endYear, self.half)

    class Meta:
        unique_together = ['faculty','startYear','endYear','half', ]


class Group(models.Model):
    groupName = models.CharField(max_length=100)
    year = models.PositiveIntegerField(default=0)
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    amount = models.SmallIntegerField(default=0)
    # course = models.SmallIntegerField(default=1)

    def __str__(self):
        return "{} : {}".format(self.groupName, self.year)

    class Meta:
        unique_together = ['groupName','year','faculty']


class Subject(models.Model):
    subjectName = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.subjectName


class Teacher(models.Model):
    lName = models.CharField(max_length=50)
    fName = models.CharField(max_length=50)
    mName = models.CharField(max_length=50)
    subject = models.ManyToManyField(Subject)

    def __str__(self):
        return "{} {} {}".format(self.lName, self.fName, self.mName)

    class Meta:
        unique_together = ['lName','fName','mName']


class StudyPlan(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject)
    semester = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return "{0} : {2} : {1}".format(self.group, self.subject, self.semester)

    class Meta:
        unique_together = ['group','subject','semester']


class VoteCounter(models.Model):
    vote = models.ForeignKey(Vote, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    course = models.PositiveSmallIntegerField(default=1)
    counter = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return '{} : {} : {} : {}'.format(self.vote, self.group, self.course, self.counter)

    class Meta:
        unique_together = ['vote','group','course']


class VoteResult(models.Model):
    vote = models.ForeignKey(Vote, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    value = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return '{} : {} : {} : {} : {}'.format(self.vote, self.subject, self.teacher, self.category, self.value)


class DeaneryResult(models.Model):
    vote = models.ForeignKey(Vote, on_delete=models.CASCADE)
    value = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return '{} : {}'.format(self.vote, self.value)

StudentPoll/forms.py
from django import forms
from StudentPoll.models import Faculty, Group, Subject, Vote, Category
from django.contrib.auth.models import User
import datetime


class SelectVoteForm(forms.Form):
    vote = forms.ModelChoiceField(
        queryset=Vote.objects.all().order_by('faculty__facultyName', 'startYear').filter(isActive=1),
        label='Опитування')
    course = forms.ChoiceField(choices=(('---------','---------'),(1,1),(2,2),(3,3),(4,4)), label='Курс')
    group = forms.ModelChoiceField(queryset=Group.objects.none(), label='Напрям')


class LoginForm(forms.Form):
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Login'}))
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))


class PollAdd(forms.Form):
    faculty = forms.ModelChoiceField(queryset=Faculty.objects.all(), label='Факультет')
    year = forms.ChoiceField(choices=[('{}/{}'.format(x, x+1),'{}/{}'.format(x, x+1))
                                           for x in range (datetime.datetime.now().year-3, datetime.datetime.now().year+1)],
                                  label='Навчальноко рік')
    half = forms.ChoiceField(choices=((1, '1'),(2, '2')), label='Семестр')
    categories = forms.ModelMultipleChoiceField(queryset=Category.objects.all(), label='Категорії оцінювання')
    isActive = forms.BooleanField(label='Активувати', required=False)


class EditState(forms.Form):
    vote = forms.ModelChoiceField(queryset=Vote.objects.all(), label='Опитування')
    activate = forms.ChoiceField(widget=forms.RadioSelect, choices=((True, 'Активувати'),(False, 'Деактивувати')),
                                 label='Стан опитування', required=True)


class SelectStatisticsVoteForm(forms.Form):
    vote = forms.ModelChoiceField(
        queryset=Vote.objects.all().order_by('faculty__facultyName', 'startYear').filter(isActive=0),
        label='Опитування')

StudentPoll/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
import datetime
from collections import defaultdict
import os.path
from django.views import View
from django.urls import reverse
from . import functions


# Create your views here.
from .forms import SelectVoteForm, LoginForm, PollAdd, EditState, SelectStatisticsVoteForm
from StudentPoll.models import Faculty, Subject, Group, StudyPlan, Teacher, Category, Vote, VoteCounter, VoteResult,\
    DeaneryResult


class Index(View):
    def get(self, request):
        print('Index_View')
        form = SelectVoteForm(initial={'f1': Faculty.objects.values('facultyName')[:1]})
        return render(request, 'StudentPoll/index.html', {'form': form, })


class Statistics(View):
    def get(self, request):
        print('statsPageGET')
        form = SelectStatisticsVoteForm(initial={'f1': Faculty.objects.values('facultyName')[:1]})
        if 'vote' in request.GET.keys():
            # form = SelectStatisticsVoteForm()
            # print(request.GET.get('vote'))
            # print(Vote.objects.get(id=request.GET['vote']), '////////////')
            v = Vote.objects.get(id=request.GET.get('vote'))
            print(v)
            file = 'StudentPoll/templates/StudentPoll/results/{}.xml'.format(str(v).replace(' : ', '_').replace('/', '!'))
            stats = None
            # if os.path.isfile(file):
            if False:
                print('exists')
                stats = file
            else:
                print('doesn\'t exists')
                functions.create_statistics_file(file, v)
                file = 'StudentPoll/templates/StudentPoll/results/{}.xml'.format(str(v).replace(' : ', '_').replace('/', '!'))
            stats = functions.read_statistics_file(file)
            # for key, value in stats.items():
            #     for k in value:
            #         print(key, k[0], k[1], sep=':: ::')
            # print(v)

            # print(stats.items())
            #
            # 'stats': stats.items()
            return render(request, 'StudentPoll/statistics.html', {'form': form,  'stats': stats})
        else:
            return render(request, 'StudentPoll/statistics.html', {'form': form, })

    def post(self, request):
        print('StatisticsViewPost')
        values_to_pop = ['csrfmiddlewaretoken','vote', 'group', 'course']
        data = request.POST.copy()
        for key, value in data.items():
            print(key, value)
        # vs = VoteCounter()
        group = Group.objects.get(id=request.POST.get('group'))
        # print(group.amount)
        vote = Vote.objects.get(id=data.get('vote'))
        vc, created = VoteCounter.objects.get_or_create(vote=vote,
                                                        group_id=data.get('group'),
                                                        course=int(data.get('course')))
        if created:
            vc.counter = group.amount

        print(vc.counter)
        if vc.counter > 0:
            for key in values_to_pop:
                if key in data:
                    data.pop(key)

            for key, value in data.items():
                if key != 'Якість роботи':

                    vr = VoteResult(vote=vote,
                                    subject=Subject.objects.get(subjectName=key.split(':')[0]),
                                    teacher=Teacher.objects.get(lName=key.split(':')[1].split(' ')[0],
                                                                fName=key.split(':')[1].split(' ')[1],
                                                                mName=key.split(':')[1].split(' ')[2]),
                                    category=Category.objects.get(categoryName=key.split(':')[2]),
                                    value=value)
                    vr.save()
                else:
                    dr = DeaneryResult(vote=vote, value=value)
                    dr.save()

            vc.counter -= 1
            vc.save()
            return HttpResponseRedirect(reverse('StudentPoll:Statistics'))
        else:
            return HttpResponseRedirect(reverse('StudentPoll:Statistics'))


class Login(View):
    print('Login_View')
    form_class = LoginForm
    template_name = 'StudentPoll/login.html'
    def get(self, request):
        print('LoginGET')
        return render(request, self.template_name, {'form': self.form_class()} )

    def post(self, request):
        print('LoginPOST')
        form = self.form_class(request.POST)
        print(form)
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username, password)
        user = authenticate(username=username, password=password)
        print(user)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('StudentPoll:PollAdmin')
        # return HttpResponseRedirect(reverse('StudentPoll:Login'))
        return render(request, self.template_name, {'error': 'An error occurred try once more', 'form': self.form_class})


class PollAdmin(LoginRequiredMixin, View):
    print('Admin_View')
    login_url = '/login/'

    def get(self, request):
        pollAdd = PollAdd
        voteActivate = EditState
        # print(form.choices)
        return render(request, 'StudentPoll/PollAdmin.html', {'pollAdd': pollAdd, 'voteActivate': voteActivate})

    def post(self, request):
        return redirect('StudentPoll:index')


class Vote_View(View):
    print('Vote_View')
    """ takes subjects and teachers and creates a vote for each subject/teacher pair"""
    def post(self, request):
        print('lalalalalalal')
        tempDict = request.POST.copy()
        fac = tempDict['faculty']
        tempDict.pop('csrfmiddlewaretoken')
        print(tempDict)
        # print(request.POST.get('faculty').split(' : ')[1].split('/')[1])
        startYear = int(request.POST.get('faculty').split(' : ')[1].split('/')[1]) - int(request.POST.get('course'))
        groupInfo = {}
        print(request.POST.items())

        # groupInfo['vote'] = Faculty.objects.get(facultyName=request.POST.get('faculty').split(' : ')[0]).id
        groupInfo['vote'] = Vote.objects.get(faculty__facultyName=request.POST.get('faculty').split(' : ')[0],
                                             startYear=request.POST.get('faculty').split(' : ')[1].split('/')[0],
                                             endYear=request.POST.get('faculty').split(' : ')[1].split('/')[1],
                                             half=request.POST.get('faculty').split(' : ')[2].split(' ')[0]
                                             ).id
        groupInfo['group'] = Group.objects.get(groupName=request.POST.get('group'), year=startYear).id
        groupInfo['course'] = request.POST.get('course')
        tempDict.pop('faculty')
        tempDict.pop('group')
        tempDict.pop('course')

        categories = Category.objects.filter(vote__faculty__facultyName=fac.split(' : ')[0],
                                             vote__startYear=fac.split(' : ')[1].split('/')[0],
                                             vote__endYear=fac.split(' : ')[1].split('/')[1],
                                             vote__half=fac.split(' : ')[2].split(' ')[0])
        print(categories)
        return render(request, 'StudentPoll/vote.html', {'subjects': tempDict.items(),
                                                         'categories': categories,
                                                         'groupInfo': groupInfo,})
    def get(self, request):
        return HttpResponse('wtf. get away')


def logout_view(request):
    logout(request)
    return redirect('StudentPoll:index')


def filterGroups_view(request):
    """ filters groups depending on "Vote" selection wich has "Faculty" in it
    @:return returns list of groups according to faculty"""
    if request.method == 'GET':
        groups = Group.objects.filter(faculty__facultyName=request.GET.get('faculty')).order_by('groupName')
        gDcit = []
        print(groups)
        for g in groups:
            if not gDcit.__contains__(g.groupName):
                gDcit.append(g.groupName)
        print(gDcit)
        if request.is_ajax():
            return JsonResponse(gDcit, safe=False)


def getSubjects_view(request):
    if request.method == 'GET':
        startYear = int(request.GET.get('year'))-int(request.GET.get('course'))
        group = Group.objects.values_list('groupName').filter(groupName=request.GET.get('group'),year=startYear)
        numberToSubstract = 0
        if request.GET.get('half') == '1':
            numberToSubstract = 1
        sem = ((int(request.GET.get('year')) - startYear) * 2) - numberToSubstract
        print(group, startYear, sem)
        print('sem {}'.format(sem))
        # DELETE THESE LINES
        # THE ARE FOR DEBUG PURPOSES
        # sem = 8 #DELETE LATER
        # UP TO HERE
        if sem != 0:
            print(4)
            subjects = StudyPlan.objects.values_list('subject__subjectName', flat=True).filter(semester=sem,
                                                                                group__groupName=request.GET.get('group'))
            try:
                if subjects[0] != '':
                    print(subjects[0])
            except IndexError:
                print('empty')
                return JsonResponse('error', safe=False)
            print(subjects)
            subjectTeacher = defaultdict(list)
            for subj in subjects:

StudentPoll/templates/StudentPoll/PollAdmin.html
{% extends "StudentPoll/header.html" %}
{% load widget_tweaks %}

{% block title %}
    Admin
{% endblock %}

{% block content %}
{#    admin stuff here#}
    <div class="well well-sm">
        <div>Додати голосування</div>
        <form action="{% url 'StudentPoll:pollAdd' %}" method="post">
        {% csrf_token %}
            {% for field in pollAdd %}
    {#            <div>{{ field|field_type }}</div>#}
                {% if field|field_type == 'booleanfield' %}
                    {{ field.label_tag }} <br> {{ field }} <br>
                {% else %}
                    {{ field.label_tag }} <br> {{ field|add_class:"form-control" }} <br>
                {% endif %}
            {% endfor %}
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>
    </div>

    <div class="well well-sm">
        <div>Додати категорію оцінювання</div>
        <form action="{% url 'StudentPoll:categoryAdd' %}" method="post">
        {% csrf_token %}
            <input class="form-control" type="text" value="" name="category" required placeholder="Категорія оцінювання">
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>
    </div>

    <div class="well well-sm">
        <div>Активувати чи деактивувати голосування</div>
        <form action="{% url 'StudentPoll:editState' %}" method="post">
        {% csrf_token %}
            {% for field in voteActivate %}
                {% if field|field_type == 'modelchoicefield' %}
                    <div>{{ field.label_tag }} {{ field|add_class:"form-control" }}</div>
                {% else %}
                    <div>{{ field.label_tag }} {{ field }}</div>
                {% endif %}
            {% endfor %}
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>
    </div>

    <form action="{% url 'StudentPoll:logout' %}" method="get">
        <input class="btn btn-danger" type="submit" value="Log Out"/>
    </form>
{% endblock %}

StudentPoll/templates/StudentPoll/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block  title%}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>


<div class="wholePageContainer pageWidth">

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid pageWidth">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Student Poll</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li id="main"{% block mainActive %}{% endblock %}><a href="/">Головна</a></li>
        <li id="statistics" {% block statisticsActive %}{% endblock %}><a href="/statistics/">Статистика</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li id="admin" {% block adminActive %}{% endblock %}><a href="/poll/admin/">Адмін</a></li>
      </ul>
    </div>
  </div>
</nav>

{% block content %}

{% endblock %}
</div>

<footer class=" footer">
    <div class="container pageWidth">
        <p class="text-muted">&#9400; footerhere</p>
    </div>
</footer>
<script src="{% static 'jquery-3.2.0.min.js' %}"></script>
<script src="{% static 'bootstrap.min.js' %}"></script>
<script src="{% static 'main.js' %}"></script>
{#<script>jQuery(document).ready(function(){console.log("loaded");});</script>#}
</body>
</html>

StudentPoll/templates/StudentPoll/index.html
{% extends "StudentPoll/header.html" %}
{#{% load static %}#}
{% load widget_tweaks %}

{% block mainActive %}
    class="active"
{% endblock %}
{% block title %}
    Creative title here
{% endblock %}

{% block content %}

    <div id="selectFac">
    {% for field in form %}
        {{ field.label_tag }} <br> {{ field|add_class:"form-control" }} <br>
    {% endfor %}

    <div id="errorMessageContainer" class="alert alert-danger" hidden></div>
    <input class="btn btn-primary" type="submit" value="Submit" id="get_subjects"/>
    </div>
    <form action="{% url 'StudentPoll:Vote' %}" method="post" name="subjectTeacher" id="subjectTeacher" class="form-group">
        {% csrf_token %}
    </form>

{% endblock %}

StudentPoll/templates/StudentPoll/login.html
{% extends "StudentPoll/header.html" %}
{% load widget_tweaks %}

{% block loginActive %}
    class="active"
{% endblock %}
{% block title %}
    Login
{% endblock %}

{% block content %}
    <div class="col-md-6 col-md-offset-3">
    		<div class="panel panel-default">
			  	<div class="panel-heading">
			    	<h3 class="panel-title">Please sign in</h3>
			 	</div>
			  	<div class="panel-body">
                    {% if error %}
                        <div class="alert alert-danger">
                        {{ error.capitalize }}
                        </div>
                    {% endif %}
			    	<form accept-charset="UTF-8" role="form" action="{% url 'StudentPoll:Login' %}" method="POST">
                        {% csrf_token %}
                    <fieldset>
			    	  	<div class="form-group">
                            {{ form.username|add_class:"form-control" }}
			    		</div>
			    		<div class="form-group">
                            {{ form.password|add_class:"form-control" }}
			    		</div>
{#			    		<div class="checkbox">#}
{#			    	    	<label>#}
{#			    	    		<input name="remember" type="checkbox" value="Remember Me"> Remember Me#}
{#			    	    	</label>#}
{#			    	    </div>#}
			    		<input class="btn btn-lg btn-info btn-block" type="submit" value="Login">
			    	</fieldset>
			      	</form>
			    </div>
			</div>
		</div>
{% endblock %}

StudentPoll/templates/StudentPoll/statistics.html
{% extends "StudentPoll/header.html" %}
{% load widget_tweaks %}

{% block statisticsActive %}
    class="active"
{% endblock %}
{% block content %}

    <form action="{% url 'StudentPoll:Statistics' %}" method="get" name="getStatistics" id="getStatistics" class="form-group">
        {% csrf_token %}
        <div id="selectFac">
        {% for field in form %}
            {{ field.label_tag }} <br> {{ field|add_class:"form-control" }} <br>
        {% endfor %}


        <input class="btn btn-primary" type="submit" value="Показати"/>

        {% if stats %}
            <div class="vote">
            {% for key in stats %}
                    <h3 class="voteCaption">{{ key }}</h3>
                    <div class="container1">
                    {% for stat in stats|get_item:key %}
                        <div class="leftHalf">
                            <div class="grow">{{ stat|get_cat:0 }}</div>
                        </div>
                        <div class="rightHalf radios">
                            <div class="grow"><label class="radio">{{ stat|get_cat:1 }}</label></div>
                        </div>
                    {% endfor %}
                    </div>
                <hr>
            {% endfor %}
            </div>
        {% endif %}
        </div>
    </form>

{#    <h1>statistics here later</h1>#}
{% endblock %}

StudentPoll/templates/StudentPoll/thanks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

StudentPoll/templates/StudentPoll/vote.html
{% extends 'StudentPoll/header.html' %}
{% load static %}

{% block title %}
    actual vote
{% endblock %}

{% block content %}
<div>
<table>
    <tr>
        <td>1</td>
        <td>Ніяк</td>
    </tr>
    <tr>
        <td>2</td>
        <td>Трохи</td>
    </tr>
    <tr>
        <td>3</td>
        <td>Добре</td>
    </tr>
    <tr>
        <td>4</td>
        <td>Гарно</td>
    </tr>
    <tr>
        <td>5</td>
        <td>Дуже гарно</td>
    </tr>
</table>
</div>
<form action="{% url 'StudentPoll:Statistics' %}" method="post">
    {% csrf_token %}
{% for key, value in groupInfo.items %}
    <input type="hidden" name="{{ key }}" value="{{ value }}">
{% endfor %}
    {% for key, value in subjects %}
            {% if key != 'Деканат'%}
                <div class="vote">
                    <div class="voteCaption">
                        {{ key }}:{{ value }}
                    </div>
                    {% for category in categories %}
                        <div class="container1">
                            <div class="leftHalf">
                                <div class="grow">{{ category }}</div>
                            </div>
                            <div class="rightHalf radios">
                                {% with ''|center:5 as range %}
                                    {% for i in range %}
                                        <input type="radio" name="{{ key }}:{{ value }}:{{ category }}" value="{{ forloop.counter }}" id="{{ key }}:{{ category }}:{{ forloop.counter }}" required />
                                        <label class="radio" for="{{ key }}:{{ category }}:{{ forloop.counter }}">{{ forloop.counter }}</label>
                                    {% endfor %}
                                {% endwith %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="vote">
                    <div class="voteCaption">
                        {{ key }}:{{ value }}
                    </div>
                    <div class="container1">
                        <div class="leftHalf">
                            <div class="grow">Якість роботи</div>
                        </div>
                        <div class="rightHalf radios">
                            {% with ''|center:5 as range %}
                                {% for i in range %}
                                    <input type="radio" name="Якість роботи" value="{{ forloop.counter }}" id="{{ key }}:Якість роботи:{{ forloop.counter }}" required/>
                                    <label class="radio" for="{{ key }}:Якість роботи:{{ forloop.counter }}">{{ forloop.counter }}</label>
                                {% endfor %}
                            {% endwith %}
                        </div>
                    </div>
                </div>

            {% endif %}
        <hr>
    {% endfor %}
    <input class="btn btn-primary" type="submit" value="Submit">
</form>

{% endblock %}